### ISSUE TITLE
[hexo]配置 - 分页数量控制

### ISSUE THREAD

**Issue by xovel** [xovel/xovel.github.io#3]
在博客根目录下的`_config.yml`中找到`per_page`部分，指定分页数量。本博客采用如下方式进行分页控制：

``` yml
# Pagination
## Set per_page to 0 to disable pagination
per_page: 8
pagination_dir: page

archive_generator:
  per_page: 20

tag_generator:
  per_page: 20

category_generator:
  per_page: 12
```
- 全局分页，每页8篇文章
- 文档归档页，每页20篇文章
- TAG页，每页20篇文章
- 分类页，每页12篇文章

> 后面三个默认配置文件中没有，加上即可。
