### ISSUE TITLE
[next]配置 - 自定义导航菜单

### ISSUE THREAD

**Issue by xovel** [xovel/xovel.github.io#6]
在主题目录下的配置文件`_config.yml`中找到`menu`，进行相应改动即可。

本博客现用菜单配置如下：

``` yml
# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# When running the site in a subdirectory (e.g. domain.tld/blog), remove the leading slash (/archives -> archives)
menu:
  home: /
  categories: /categories
  tags: /tags
  archives: /archives
  about: /about
  #commonweal: /404.html
  garden: /garden


# Enable/Disable menu icons.
# Icon Mapping:
#   Map a menu item to a specific FontAwesome icon name.
#   Key is the name of menu item and value is the name of FontAwsome icon. Key is case-senstive.
#   When an question mask icon presenting up means that the item has no mapping icon.
menu_icons:
  enable: true
  #KeyMapsToMenuItemKey: NameOfTheIconFromFontAwesome
  home: home
  about: user
  categories: th
  tags: tags
  archives: archive
  commonweal: heartbeat
  garden: life-ring
```

> `menu_icons`对应的是菜单的图标。使用`FontAwesome icon`。
