### ISSUE TITLE
[next]配置 - 添加外部链接高亮效果

### ISSUE THREAD

**Issue by xovel** [xovel/xovel.github.io#7]
`\source\css\_common\components\post\post.styl`添加以下代码：

``` css
.post-body a[rel~="external"] {
  color: #3370BB;
}
.post-body a[rel~="external"]:after {
  content:"\f08e";
  font: normal normal normal 14px/1 FontAwesome;
  margin-left:2px;
}
```
